export const APP_INIT = "APP_INIT";

export const USER_JOIN_SUCCESS = "USER_JOIN_SUCCESS";
export const USER_JOIN_ERROR = "USER_JOIN_ERROR";

export const USER_LEAVE_SUCCESS = "USER_LEAVE_SUCCESS";
export const USER_LEAVE_ERROR = "USER_LEAVE_ERROR";

export const ARENA_FETCH_SUCCESS = "ARENA_FETCH_SUCCESS";
export const ARENA_FETCH_ERROR = "ARENA_FETCH_ERROR";

export const ACTIONS_SET = "ACTIONS_SET";
export const ACTIONS_RESET = "ACTIONS_RESET";
export const ACTIONS_SUBMIT_SUCCESS = "ACTIONS_SUBMIT_SUCCESS";
export const ACTIONS_SUBMIT_ERROR = "ACTIONS_SUBMIT_ERROR";